[project]
name = "maisivae"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "monai[nibabel,tqdm]>=1.5.1",
    "scikit-image>=0.25.2",
    "simpleitk>=2.5.2",
]
